### ISSUE TITLE
MODELO DE NEGOCIO

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-v-a-k#1]
[PRACTICA 4 Modelo Negocios CANVA.pdf](https://github.com/user-attachments/files/17122473/PRACTICA.4.Modelo.Negocios.CANVA.pdf)

**Comment by edgarmauricio123** [comment]
Cumple con lo requerido en la rubrica 20 de 20 .

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
